# Generated by Django 6.0.7 on 2026-07-29 23:06

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mrn', models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='File number')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other or not stated')], default='O', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Use digits, spaces, and + ( ) - only.', regex='^[\\d+()\\-\\s]{5,20}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village or area')),
                ('address', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True, help_text='Anything that must be seen before prescribing. Leave empty if none known.')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck instead of deleting when someone moves away or dies.', verbose_name='Currently under care')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='records_pat_last_na_5c97b9_idx'), models.Index(fields=['dob'], name='records_pat_dob_d80ea5_idx')],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'dob'), name='unique_patient_identity', violation_error_message='A patient with this name and date of birth already exists.')],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('clerk', 'Records clerk'), ('admin', 'Administrator')], default='nurse', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Use digits, spaces, and + ( ) - only.', regex='^[\\d+()\\-\\s]{5,20}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=200, verbose_name='Reason for visit')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'In progress'), ('closed', 'Finished'), ('referred', 'Referred on')], default='open', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='records.patient')),
                ('seen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 500 mg, twice daily', max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if ongoing.', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='records.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='records.visit')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('icd_code', models.CharField(blank=True, max_length=20, verbose_name='ICD-10 code')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='records.visit')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['-date'], name='records_vis_date_e6fb57_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='records_vis_status_aad174_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['patient', '-start_date'], name='records_med_patient_12b42f_idx'),
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='medication_ends_after_start'),
        ),
    ]
